services:
  postgresql:
    image: postgis/postgis:14-3.2
    platform: linux/amd64  # Force compatibility
    command: postgres -c 'max_connections=3500'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: running_app
      POSTGRES_PASSWORD: running_app!
    ports:
      - "5432:5432"

  redis:
    image: redis:4.0
    restart: always
    ports:
      - "6379:6379"