services:
  postgresql:
    image: postgis/postgis:14-3.2
    command: postgres -c 'max_connections=3500'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: hackathon
      POSTGRES_PASSWORD: hackathon1!
    ports:
      - "5432:5432"

  redis:
    image: redis:4.0
    restart: always
    ports:
      - "6379:6379"


  # zookeeper:
  #   image: zookeeper:3.7.0
  #   container_name: local-zookeeper
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     ZOO_MY_ID: 1
  #     ZOO_PORT: 2181
  #     ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  # kafka:
  #   image: bitnami/kafka:2.6.0
  #   container_name: local-kafka
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     - KAFKA_ENABLE_KRAFT=yes
  #     - KAFKA_CFG_PROCESS_ROLES=broker,controller
  #     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
  #     - KAFKA_BROKER_ID=1
  #     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes