"""added title to path


Revision ID: 21a4f12de1eb
Revises: 9b52b0923fed
Create Date: 2024-11-10 04:22:12.358210

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "21a4f12de1eb"
down_revision: Union[str, None] = "9b52b0923fed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "path",
        sa.Column(
            "title", sa.String(), nullable=False, server_default=sa.text("'테스트'")
        ),
    )

    op.add_column("path", sa.Column("description", sa.String(), nullable=True))


# ## ### end Alembic commands ###
