"""removed not null path_id

Revision ID: 882213068e14
Revises: 21a4f12de1eb
Create Date: 2024-11-10 04:44:55.461730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "882213068e14"
down_revision: Union[str, None] = "21a4f12de1eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "run",
        "total_distance",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column("run", "path_identifier", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
