"""crew, crew_memeber

Revision ID: 9b52b0923fed
Revises: 87a5eb90ca59
Create Date: 2024-11-10 03:16:27.873036

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9b52b0923fed"
down_revision: Union[str, None] = "87a5eb90ca59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crew",
        sa.Column("identifier", sa.Uuid(), nullable=False),
        sa.Column("crew_name", sa.String(), nullable=False),
        sa.Column("version_uuid", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("identifier"),
    )
    op.create_table(
        "crew_member",
        sa.Column("identifier", sa.Uuid(), nullable=False),
        sa.Column("user_identifier", sa.Uuid(), nullable=False),
        sa.Column("crew_identifier", sa.Uuid(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("member_status", sa.String(), nullable=False),
        sa.Column("version_uuid", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["crew_identifier"],
            ["crew.identifier"],
        ),
        sa.ForeignKeyConstraint(
            ["user_identifier"],
            ["user.identifier"],
        ),
        sa.PrimaryKeyConstraint("identifier"),
    )

    # ### end Alembic commands ###
